server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: postgres
    password: gun1915gnir
  
  jpa: 
    hibernate:
      ddl-auto: update     
    show-sql: true  
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQL9Dialect
    
    
#5432 posgre port gun1915gnir
    
    