
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_db?serverTimezone=Mexico/General
    username: root
    password: gun1915gnir
  
  jpa: 
    hibernate:
      ddl-auto: update     
    show-sql: true  
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
    
    
#5432 posgre port gun1915gnir
    
    